"""
Universal Director — Fully LLM-Driven Video Pipeline

Usage:
    python run_universal.py cooking
    python run_universal.py fitness  
    python run_universal.py meditation
    python run_universal.py travel

How it works:
1. Opens Chromium browser → gemini.google.com (uses your logged-in account)
2. Asks Gemini to WRITE the complete HTML/CSS/JS animation code
3. Asks Gemini to WRITE the voiceover narration
4. Generates audio + subtitles via Edge-TTS
5. Records the animation + composes final MP4 video

NOTHING is hardcoded — Gemini decides everything by itself.
"""

import sys
import os

# Ensure the project root is in the path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from agents.universal_director import UniversalDirectorAgent


def main():
    if len(sys.argv) < 2:
        print("=" * 50)
        print("  Universal Director — AI Video Pipeline")
        print("  Everything generated by Web Gemini")
        print("=" * 50)
        print()
        print("Usage: python run_universal.py <topic>")
        print()
        print("Examples:")
        print("  python run_universal.py cooking")
        print("  python run_universal.py fitness")
        print("  python run_universal.py meditation")
        print("  python run_universal.py travel")
        print("  python run_universal.py gaming")
        print()
        
        topic = input("Enter a topic (or press Enter for 'cooking'): ").strip()
        if not topic:
            topic = "cooking"
    else:
        topic = " ".join(sys.argv[1:])
    
    agent = UniversalDirectorAgent()
    output = agent.run(topic)
    
    print(f"\nFinal video: {output}")


if __name__ == "__main__":
    main()
