"""Root prompts module re-exporting all prompt templates."""

from agents.release_intelligence.prompts import (
    RELEASE_NOTES_CUSTOMER_PROMPT,
    RELEASE_NOTES_ENGINEERING_PROMPT,
    RELEASE_NOTES_EXECUTIVE_PROMPT,
    RELEASE_NOTES_TECHNICAL_PROMPT,
    IMPACT_ANALYSIS_SYSTEM_PROMPT,
    BREAKING_CHANGES_PROMPT,
    CUSTOMER_SUMMARY_PROMPT,
    DEVELOPER_SUMMARY_PROMPT,
    RISK_ANALYSIS_PROMPT,
)

__all__ = [
    "RELEASE_NOTES_CUSTOMER_PROMPT",
    "RELEASE_NOTES_ENGINEERING_PROMPT",
    "RELEASE_NOTES_EXECUTIVE_PROMPT",
    "RELEASE_NOTES_TECHNICAL_PROMPT",
    "IMPACT_ANALYSIS_SYSTEM_PROMPT",
    "BREAKING_CHANGES_PROMPT",
    "CUSTOMER_SUMMARY_PROMPT",
    "DEVELOPER_SUMMARY_PROMPT",
    "RISK_ANALYSIS_PROMPT",
]
