"""Impact Analysis models generated by AI reasoning."""

from typing import List
from pydantic import BaseModel, Field


class UserImpact(BaseModel):
    """Business and end-user impact description."""
    summary: str = Field(description="Summary of user-facing changes")
    affected_user_roles: List[str] = Field(default_factory=list, description="Roles impacted (e.g., End Users, Admins)")
    workflow_changes: List[str] = Field(default_factory=list, description="Key workflows modified for users")


class DeveloperImpact(BaseModel):
    """Technical and developer impact description."""
    summary: str = Field(description="Summary of developer/technical impacts")
    api_changes: List[str] = Field(default_factory=list, description="API contract alterations")
    schema_changes: List[str] = Field(default_factory=list, description="Schema or permission changes")


class DocumentationRecommendation(BaseModel):
    """Recommendation for Documentation Agent."""
    section_to_update: str = Field(description="Target doc section or topic")
    reason: str = Field(description="Why doc update is required")
    priority: str = Field(default="Medium", description="High, Medium, Low")


class QARecommendation(BaseModel):
    """Recommendation for QA Agent."""
    test_area: str = Field(description="Component or workflow to test")
    recommendation_type: str = Field(description="New Test, Regression, Update Script")
    reason: str = Field(description="Reason for QA test regeneration")


class DemoRecommendation(BaseModel):
    """Recommendation for Demo Agent."""
    feature_or_flow: str = Field(description="Demo scene or feature flow")
    action_required: str = Field(description="Add scene, update walkthrough, remove script")
    reason: str = Field(description="Rationale for demo update")


class ImpactAnalysis(BaseModel):
    """Aggregate AI-reasoned Impact Analysis model."""
    user_impact: UserImpact
    developer_impact: DeveloperImpact
    doc_recommendations: List[DocumentationRecommendation] = Field(default_factory=list)
    qa_recommendations: List[QARecommendation] = Field(default_factory=list)
    demo_recommendations: List[DemoRecommendation] = Field(default_factory=list)
